version: "3"
networks:
  expense:
volumes:
  mysql:  # docker volume create mysql
services:
  mysql:
    image: joindevops/mysql:v1
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: joindevops/backend:v1
    container_name: backend
    depends_on:
    - mysql
  frontend:
    image: joindevops/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend